version: "3.8"
services:
  web:
    build: ./flask-app
    ports:
      - "5000:5000"
    depends_on:
      - redis
  redis:
    image: redis:7
    volumes:
      - redis_data:/data
volumes:
  redis_data: