version: "3.8"
services:
  web:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - db
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: demo
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data: