version: "3.8"
services:
  web:
    build: ./node-app
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: mongo:6
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data: