# This manifest file contains two Kubernetes resources: a StorageClass and a PersistentVolumeClaim (PVC).
# The StorageClass named "fast-storage" uses the "kubernetes.io/no-provisioner" provisioner and has a volume binding mode of "WaitForFirstConsumer".
# The PVC named "dynamic-pvc" requests 1Gi of storage with ReadWriteOnce access mode and uses the "fast-storage" StorageClass. 
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dynamic-pvc
spec:
  storageClassName: fast-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi